### ISSUE TITLE
How to adjust "auth-server-url" at runtime

### ISSUE THREAD

**Issue by NiklasA** [dasniko/testcontainers-keycloak#11]
Hi @dasniko,

I really like your Keycloak Testcontainer. Is there an easy way to adjust the "keycloak.auth-server-url" property in my "application.yaml" in my integration tests at runtime? Because otherwise, my application does not know how it could validate e.g. a given access token.

My workaround was to customize your Java class "KeycloakContainer" and change this class to extend FixedHostPortGenericContainer instead of GenericContainer. However, it seems to me that I should not be the only one (hopefully ;-) with this problem.

My current project setup:
- Spring Boot (Java)
- Spock testing framework (Groovy)

Thank you in advance.

BR
Niklas

**Comment by dasniko** [comment]
Hi Niklas,
Happy to hear that you like the Keycloak Testcontainer.

So, your question is about how to configure your application framework and its testing resources, not about Keycloak Testcontainers, as this is a general requirement when using Testcontainers, nothing special with the Keycloak Testcontainer (e.g when using DB testcontainers, you also have to adjust host/port/credentials somehow).

For Spring based applications, I already answered this [in this comment](https://github.com/dasniko/testcontainers-keycloak/issues/8#issuecomment-719551847). It‘s always a good thing to know the used stack and its testing possibilities. 😉

**Comment by dasniko** [comment]
Closing this issue as there is no feedback.
