### ISSUE TITLE
Add support for verbose command line argument

### ISSUE THREAD

**Issue by raoulvdberge** [dasniko/testcontainers-keycloak#114]
### Description

Often, when doing extension dev, something fails:
```
[docker-java-stream-1064091640] INFO tc.quay.io/keycloak/keycloak:22.0.1 - STDOUT: 2023-09-08 08:22:27,244 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```
To see the entire stack trace, I'd need to set the `--verbose` option. Currently, it does not seem possible to enable this.

**Comment by dasniko** [comment]
Thanks for this issues.
Makes sense IMHO, especially when this testcontainer is used for development.

**Comment by dasniko** [comment]
There are currently some other issues/features in development. If they are some kind of done, or, when a new KC major version will be released, I'll do a new release.
