### ISSUE TITLE
Dependency on quarkus-junit4-mock causes issues with projects actually depending on junit4

### ISSUE THREAD

**Issue by carstenlenz** [dasniko/testcontainers-keycloak#124]
### Describe the bug

This project has a dependency on quarkus-junit4-mock because testcontainers (sadly) has a dependency on junit4. 

Problem is that when like in my case there is some 3rd party also relying on junit4. Some unlucky classpath ordering will then ruin my day when the 3rd party lib is getting the mock stuff and give me `NoSuchMethodError`s confusing me (of course IntelliJ has it's own opinion on what should be navigated to and jumped to the actual JUnit lib during error investigation which increased my confusion).

I admit I don't really know how to handle this other then keeping the correct junit4 dependency instead of the mock one. In my case I can exclude the mock lib now of course. It's just not obvious at all that this is being done. Is adding something to the docs an option?

### Version

2.5.0

### Expected behavior

Either no mock dependency is part of the compile dependencies or it is documented that this is done. 

Thank you :)
Carsten

**Comment by dasniko** [comment]
Hi @carstenlenz, thanks for coming up with this.
Having the mock dependency is the way of least pain, IMHO. Removing the dependency, other implications will come up, guaranteed.
So, I would vote for adding a paragraph to the README, that this dependency is there.
Hopefully, Testcontainers will remove this dependency with 2.x and this will released soon.

If you have a proposal for the README, you're welcome to create a PR!

**Comment by carstenlenz** [comment]
Yep - [here you go](#125)

**Comment by dasniko** [comment]
thanks! 👍
