### ISSUE TITLE
version 3.4.0 requires jackson dependency that is not provided

### ISSUE THREAD

**Issue by monzonj** [dasniko/testcontainers-keycloak#148]
### Describe the bug

Create a project and include testcontainers-keycloak:3.4.0

create a simple test such as:

```
import dasniko.testcontainers.keycloak.KeycloakContainer;
import org.junit.jupiter.api.Test;

public class KeycloakContainerExtensionTest {
    @Test
    public void shouldStartKeycloak() {
        try (var keycloak = new KeycloakContainer()
                .withProviderClassesFrom("target/classes")) {
            keycloak.start();
        }
    }
}
```

when you try to run it, you get the runtime exception:

```
java.lang.ClassNotFoundException: com.fasterxml.jackson.annotation.JsonView
```

This does not happen with version 3.3.0

### Version

3.4.0

### Expected behavior

library should provided needed libs

**Comment by dasniko** [comment]
Thanks for your issue.
Please provide a minimal reproduceable example project, where this happens, not just an excerpt of the the code. Thank you.
