### ISSUE TITLE
[KC-26] admin environment variables need to be adjusted

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [dasniko/testcontainers-keycloak#152]
### Describe the bug

With Keycloak 26 the environment variables need to be adjusted. It is currently not working with the current keycloak SNAPSHOT version anymore:

```
KC_BOOTSTRAP_ADMIN_USERNAME=admin
KC_BOOTSTRAP_ADMIN_PASSWORD=admin
```

instead of

```
KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=admin
```

### Version

3.4.0

**Comment by dasniko** [comment]
Thanks for reporting this.
I don't consider this as a bug, but as an enhancement, as this is a new feature Keycloak will introduce with v26.

Also, I can't reproduce that the current legacy env vars doesn't work anymore (as they are "only" deprecated, but not yet removed), as the regular tests against the `nightly` image with `999.0.0-SNAPSHOT` dependencies still succeed (main branch).
