### ISSUE TITLE
Support Java 11 or even Java 8

### ISSUE THREAD

**Issue by odzhychko** [dasniko/testcontainers-keycloak#158]
### Description

Consider supporting Java 11 or even Java 8.

### Motivation

Make the Keycloak module usable in projects that require older Java versions.

### Details

Currently the module requires at least Java 17.

```
dasniko/testcontainers/keycloak/KeycloakContainer has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

Testcontainers seems to support Java 8.
See https://github.com/testcontainers/testcontainers-java/blob/04206d9dff440e875906f01151f09ad04da3c68f/build.gradle#L39

**Comment by dasniko** [comment]
I won't do this as both Java versions are old, outdated and out of service. I always want to encourage people to upgrade their environments and use more uptodate versions of their software products.
Other libraries/projects might do it differently, yes, but I won't. I'll stick with Java 17 for now.
Yes, that's opinionated, I know. But what in life is not!?
(and yes, I might be a bit sarcastic)
