### ISSUE TITLE
Version 3.5.0 not available on maven central

### ISSUE THREAD

**Issue by ZIRAKrezovic** [dasniko/testcontainers-keycloak#159]
### Describe the bug

Forgive me if I noticed this too early, but the version 3.5.0 was tagged earlier today, yet it is not available on maven central (via sonatype)

https://central.sonatype.com/artifact/com.github.dasniko/testcontainers-keycloak/overview
https://mvnrepository.com/artifact/com.github.dasniko/testcontainers-keycloak

### Version

3.5.0

**Comment by dasniko** [comment]
It's now available.
