### ISSUE TITLE
Support for vault-dir on TestContainers

### ISSUE THREAD

**Issue by raihans8379** [dasniko/testcontainers-keycloak#162]
### Description

Hello,

I am curious whether using https://www.keycloak.org/server/vault is supported on TestContainers, I do not see a reference to this in the code or in any github issues.

It seems according to this StackOverflow post: https://stackoverflow.com/questions/78196298/how-to-utilize-vault-feature-in-keycloak, this feature may only be available on production mode and not dev mode (TestContainers run in dev mode i.e. `start-dev`).

This feature might be useful to testing out loading secrets, but wonder if it is an issue in general with Keycloak, or only with TestContainers.

Thanks!

**Comment by dasniko** [comment]
This project is not a re-implementation of Keycloak, it just uses the regular image and has a few convenience methods around. You can still configure everything you want, like in your regular Keycloak environment, but just for test cases. You can use env vars and custom command line arguments.
If you read the docs carefully of this project, you'd have seen that there's also a production mode available: https://github.com/dasniko/testcontainers-keycloak#starting-in-production-mode

**Comment by raihans8379** [comment]
Thank you for the speedy response @dasniko -- I don't think this was actually a good question.

TestContainers are able to mount a secrets directory and configure the vault out of the box with something like this
```
KeycloakContainer kc_container = new KeycloakContainer("quay.io/keycloak/keycloak:...")
            .withCopyFileToContainer(
                    MountableFile.forClasspathResource("/local_path/secret_name"),
                    "secrets_dir_on_kc_container/"
            )
            .withCustomCommand("--vault=file")
            .withCustomCommand("--vault-file=secrets_dir_on_kc_container/secret_name")
            ...
```

My real issue was something else: referring to oidc client, client secrets via the vault.
Keycloak does not yet support this:
- https://keycloak.discourse.group/t/retrieve-keycloak-oidc-client-secret-from-vault-provider/12983
- https://github.com/keycloak/keycloak/issues/13102

So the original issue was already solved on TestContainers, but not yet supported by KeyCloak.

I will close this non-issue -- thanks!
