### ISSUE TITLE
Outdated Keycloak version compatibility documentation

### ISSUE THREAD

**Issue by daniel-shuy** [dasniko/testcontainers-keycloak#163]
### Describe the bug

- `testcontainers-keycloak` `3.4.x` only supports Keycloak `25.x`+ due to the wait strategy being changed to use the health endpoint (https://github.com/dasniko/testcontainers-keycloak/commit/455a5dff2bd0a59876605a9a3cd3783130794b64)
- `testcontainers-keycloak` `3.5.x` only supports Keycloak `26.x`+ due to the admin credentials environment variable change (https://github.com/dasniko/testcontainers-keycloak/commit/d35417fe85c98150388fa6d46c3862ad462fca9b).

### Version

3.5.1

### Expected behavior

The `README` should be updated to document the version compatibility, e.g.

| testcontainers-keycloak version | Keycloak version |
| -- | -- |
| 3.5.x | 26.x+ |
| 3.4.x | 25.x |
| 3.0.x-3.3.x | 22.x-25.x |
| 2.x.x | 17.x-22.x |

### Actual behavior

The `README` currently documents that the current `testcontainers-keycloak` version (`3.5.1` at time of writing) supports Keycloak `22.x` and up:

> This version only handles Keycloak from version 22.x and up, as there are major changes coming with this release. See also the [blog post](https://www.keycloak.org/2023/07/keycloak-2200-released.html).
For older Keycloak versions (until 21.x), see [version 2.x branch](https://github.com/dasniko/testcontainers-keycloak/tree/v2).

**Comment by dasniko** [comment]
I think what you're looking for is already here: https://github.com/dasniko/testcontainers-keycloak?tab=readme-ov-file#testcontainers--keycloak-version-compatiblity
!?

**Comment by daniel-shuy** [comment]
Oh oops, my bad. Perhaps the statement at the top of the `README` could be changed to:

> Version 3.x only handles Keycloak from version 22.x and up, as there are major changes coming with this release. See also the [blog post](https://www.keycloak.org/2023/07/keycloak-2200-released.html).
For older Keycloak versions (until 21.x), see [version 2.x branch](https://github.com/dasniko/testcontainers-keycloak/tree/v2).
