### ISSUE TITLE
Update to keycloak 12.0.4

### ISSUE THREAD

**Issue by thomasdarimont** [dasniko/testcontainers-keycloak#20]

**Comment by dasniko** [comment]
Thanks.
I'll merge this, as this is not a game changer.

But WDYT about keeping align with all the patch versions?
I don't think we need a new testcontainers-keycloak version with every new KC version. Major versions yes, minor possibly also (although there wasn't a minor version in the past since changing the versioning schema beginning with v5), but not necessarily patch version, until they will fix a certain issue.

**Comment by thomasdarimont** [comment]
Thanks for the quick response :)

I'd opt to maintain a version compatibility table in the readme.me and keep the library versioning independent of the supported Keycloak version to keep the versioning scheme straight forward.

As you suggest, I'd do a major version bump of the library whenever the underlying Keycloak version does a major version bump. The rest can be handled with minor or patch version bumps of the library.

**Comment by dasniko** [comment]
This table already exists: https://github.com/dasniko/testcontainers-keycloak#testcontainers--keycloak-version-compatiblity

**Comment by thomasdarimont** [comment]
I know, that's why I edited the table in this PR :) just wanted to point out that I think this is the way to go.

**Comment by dasniko** [comment]
I didn't mean to change the major version of this library when the major version of KC changes. I want to avoid this. A major version change of KC should only result in a minor version change of `tc-kc`.

What I wanted to discuss is, if we really need a new version of the lib on every KC patch version. IMHO this is only needed if the patch really fixes an issue which will make the library fail. But most of the patch versions of KC didn't solve anything we need in a testcontainer.

**Comment by thomasdarimont** [comment]
Oh, apparently I miss-understood this part: `Major versions yes, minor possibly also, but not necessarily patch version, until they will fix a certain issue.`

Your suggestion makes sense to me.
