### ISSUE TITLE
Support for keycloak 10.x.x

### ISSUE THREAD

**Issue by aqp696** [dasniko/testcontainers-keycloak#4]
Please could you generate a new release 1.3.2 with support for keycloak v10.x.x

**Comment by dasniko** [comment]
Hi,
just released it to the Sonatype repository. Please allow some time until it is publicly available.

**Comment by dasniko** [comment]
Sorry, made a mistake, will have to release another version...

**Comment by dasniko** [comment]
So now there's release **1.3.3** which contains Keycloak 10.0.2
