### ISSUE TITLE
Please rev the major version instead of the minor version for new major versions of keycloak

### ISSUE THREAD

**Issue by jmax01** [dasniko/testcontainers-keycloak#81]
### Description

Please rev the major version instead of the minor version for new major versions of keycloak.

Teams that rely on automated dependency management tools (dependabot, etc) most often set these tools to update by minor version since the majority of projects follow Semver versioning schemes.

The current versioning scheme is incompatible with Semver leading teams to perform workarounds for testcontainers-keycloak.

**Comment by dasniko** [comment]
You can mitigate version conflicts with setting an explicit Keycloak image when creating the container, e.g. `new KeycloakContainer("quay.io/keycloak/keycloak:18.0.0");` 
This way, the testcontainer doesn't use the most recent default image, like specified in the code.

Additionally, when using the `keycloak-admin-client` dependency, you can exclude the default one and add the desired version to your dependency list.

**Comment by jmax01** [comment]
That only works if the commands/flags in [KeycloakContainer](https://github.com/dasniko/testcontainers-keycloak/blob/bc831c5c4b1e97ded78e7c5cf9f144d0438e794d/src/main/java/dasniko/testcontainers/keycloak/KeycloakContainer.java) stay the same between versions.

To me it seems safer and more user friendly to keep MAJOR and MINOR versions incrementing with keycloak's.

**Comment by dasniko** [comment]
I decided against aligning the `testcontainers-keycloak` extension with Keycloak versioning. I'd would clash if we need a patch/minor update of this lib and shortly after this, Keycloak would publish a patch or minor release.

But FWIW, I made the method `getKeycloakDefaultVersion()` public, as mentioned by @markbanierink
