### ISSUE TITLE
Inject system properties into Docker environment

### ISSUE THREAD

**Issue by EvgeniGordeev** [dasniko/testcontainers-keycloak#93]
### Description

Is there a way to inject `-Dkeycloak.migration.strategy=OVERWRITE_EXISTING` ?

### Motivation

Further customization of docker setup to provide more flexible ways of tailoring the KC configuration.

### Details

In our tests we need to override master realm with a predefined configuration file.

**Comment by dasniko** [comment]
The `-Dkeycloak.migration.strategy` is an option from the legacy (Wildfly) Keycloak distribution. The current version (2.x) from this project doesn't support the legacy Keycloak anymore. Only the Quarkus distribution is supported. And with Quarkus, import on startup can only import new realms, no overwrites are possible, AFAIK. Other imports need a custom lifecycle of the container, which is not supported by this extension.

**Comment by EvgeniGordeev** [comment]
@dasniko you are right. After some debugging of quarkus distribution I found out that it's exactly the way you describe.
